import type {
  LearningCategory,
  SourceAttribution,
} from "@/features/wallpaper/types";

type LessonSeed = readonly [term: string, definition: string, fact: string];
type LessonQuote = readonly [text: string, author: string];

export const lessonQuotes: readonly LessonQuote[] = [
  ["The impediment to action advances action.", "Marcus Aurelius"],
  ["No man is free who is not master of himself.", "Epictetus"],
  ["Luck is what happens when preparation meets opportunity.", "Seneca"],
  ["Well done is better than well said.", "Benjamin Franklin"],
  ["Nothing will work unless you do.", "Maya Angelou"],
  ["The beginning is the most important part of the work.", "Plato"],
  ["Our life is what our thoughts make it.", "Marcus Aurelius"],
  ["Make the most of yourself, for that is all there is of you.", "Ralph Waldo Emerson"],
  ["The secret of getting ahead is getting started.", "Mark Twain"],
  ["Great things are done by a series of small things brought together.", "Vincent van Gogh"],
  ["It is never too late to be what you might have been.", "George Eliot"],
  ["Do what you can, with what you have, where you are.", "Theodore Roosevelt"],
  ["The way to get started is to quit talking and begin doing.", "Walt Disney"],
  ["Energy and persistence conquer all things.", "Benjamin Franklin"],
  ["Act as if what you do makes a difference. It does.", "William James"],
  ["The future depends on what you do today.", "Mahatma Gandhi"],
  ["What we think, we become.", "Traditional proverb"],
  ["An investment in knowledge pays the best interest.", "Benjamin Franklin"],
  ["The only way out is through.", "Robert Frost"],
  ["Simplicity is the ultimate sophistication.", "Traditional attribution"],
  ["A journey of a thousand miles begins with a single step.", "Traditional proverb"],
  ["Do the thing and you will have the power.", "Ralph Waldo Emerson"],
  ["Lost time is never found again.", "Benjamin Franklin"],
  ["The reward of a thing well done is having done it.", "Ralph Waldo Emerson"],
  ["He who has a why can bear almost any how.", "Friedrich Nietzsche"],
  ["What you do speaks so loudly that I cannot hear what you say.", "Ralph Waldo Emerson"],
  ["Success is the sum of small efforts, repeated day in and day out.", "Robert Collier"],
  ["There is no substitute for hard work.", "Thomas Edison"],
  ["The best way out is always through.", "Robert Frost"],
  ["We become what we repeatedly do.", "Traditional attribution"],
] as const;

export const quoteSource: SourceAttribution = {
  label: "Public-domain and attributed quotations",
  url: "https://en.wikisource.org/wiki/Wikisource:Quotations",
  license: "Public domain / attributed",
};

export const sourceByCategory: Record<
  LearningCategory,
  SourceAttribution
> = {
  vocabulary: {
    label: "Wiktionary",
    url: "https://en.wiktionary.org/",
    license: "CC BY-SA 4.0",
  },
  coding: {
    label: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development",
    license: "CC BY-SA 2.5",
  },
  finance: {
    label: "Investor.gov",
    url: "https://www.investor.gov/introduction-investing",
    license: "U.S. government resource",
  },
  stoicism: {
    label: "Wikisource classical texts",
    url: "https://en.wikisource.org/wiki/Author:Marcus_Aurelius",
    license: "Public domain",
  },
  science: {
    label: "NASA Science",
    url: "https://science.nasa.gov/",
    license: "U.S. government resource",
  },
  history: {
    label: "Wikipedia history portal",
    url: "https://en.wikipedia.org/wiki/Portal:History",
    license: "CC BY-SA 4.0",
  },
  psychology: {
    label: "Wikipedia psychology portal",
    url: "https://en.wikipedia.org/wiki/Portal:Psychology",
    license: "CC BY-SA 4.0",
  },
  productivity: {
    label: "WallCab editorial",
    url: "https://wallcab.dhruvdev.me/sources",
    license: "CC BY 4.0",
  },
};

export const fallbackSeeds: Record<
  LearningCategory,
  readonly LessonSeed[]
> = {
  vocabulary: [
    ["Sonder", "The realization that every passerby has a life as vivid and complex as your own.", "Use it to replace a quick judgment with curiosity."],
    ["Liminal", "Relating to a threshold or an in-between stage.", "Dawn, doorways, and life transitions can all feel liminal."],
    ["Epiphany", "A sudden, illuminating realization.", "Writing an insight down quickly helps preserve its useful detail."],
    ["Serendipity", "A fortunate discovery made by chance.", "Curiosity increases the odds of noticing a useful accident."],
    ["Lucid", "Clear, easy to understand, or mentally alert.", "A lucid explanation removes complexity without removing truth."],
    ["Tenacious", "Persistent in maintaining or seeking something valued.", "Tenacity works best when paired with feedback."],
    ["Ephemeral", "Lasting for a very short time.", "A rainbow is a familiar example of ephemeral beauty."],
    ["Pragmatic", "Focused on practical results rather than theory alone.", "Pragmatic choices still benefit from clear principles."],
    ["Eloquent", "Fluent, persuasive, and graceful in expression.", "Precise words often make speech more eloquent than extra words do."],
    ["Resilient", "Able to recover or adapt after difficulty.", "Recovery time is part of resilience, not evidence against it."],
    ["Ubiquitous", "Present, appearing, or found everywhere.", "Smartphones became ubiquitous within a few decades."],
    ["Meticulous", "Showing careful attention to small details.", "Checklists turn meticulous thinking into a repeatable habit."],
    ["Benevolent", "Well-meaning, kind, and inclined to help.", "Benevolence describes intent as well as action."],
    ["Ambivalent", "Having mixed or contradictory feelings about something.", "Ambivalence is different from indifference; both sides matter."],
    ["Candid", "Truthful and straightforward without concealment.", "Candid feedback is most useful when it is also specific."],
    ["Diligent", "Steady, careful, and persistent in one’s work.", "Diligence compounds through small sessions repeated often."],
    ["Frugal", "Careful about using money or resources without waste.", "Frugal does not mean cheapest; it means deliberate value."],
    ["Gregarious", "Fond of company and naturally sociable.", "The word traces to the Latin term for a flock."],
    ["Humble", "Having a modest view of one’s importance while remaining open to learning.", "Humility makes it easier to update a mistaken belief."],
    ["Judicious", "Showing good judgment and balanced consideration.", "A judicious decision weighs consequences, evidence, and timing."],
    ["Kinetic", "Relating to motion or movement.", "Kinetic energy depends on both mass and velocity."],
    ["Magnanimous", "Generous and forgiving, especially toward a rival.", "Magnanimity is strength expressed without pettiness."],
    ["Nuanced", "Characterized by subtle distinctions or variations.", "Nuanced thinking can hold two partly true ideas at once."],
    ["Obsolete", "No longer used because something newer has replaced it.", "A technology can be obsolete while its underlying idea remains useful."],
    ["Paradox", "A statement or situation that seems contradictory yet may reveal a truth.", "Paradoxes expose hidden assumptions in everyday reasoning."],
    ["Quaint", "Attractively old-fashioned or unusual.", "Context decides whether quaint feels affectionate or dismissive."],
    ["Robust", "Strong, healthy, or able to withstand changing conditions.", "A robust system handles ordinary failures without collapsing."],
    ["Succinct", "Clearly expressed in few words.", "Succinct writing usually comes from editing, not from rushing."],
    ["Versatile", "Able to adapt to many different functions or activities.", "A versatile skill transfers across projects and roles."],
    ["Wistful", "Quietly longing for something absent or past.", "Wistful describes a gentle blend of sadness and affection."],
  ],
  coding: [
    ["Algorithm", "A finite sequence of steps for solving a problem.", "A correct algorithm can still be impractical if it scales poorly."],
    ["Abstraction", "A simplified interface that hides unnecessary implementation detail.", "Good abstractions reveal what matters and conceal what can change."],
    ["API", "A documented interface through which software systems communicate.", "An API contract includes errors and limits, not only successful responses."],
    ["Cache", "Stored data reused to avoid repeating expensive work.", "Every cache needs an expiration or invalidation strategy."],
    ["Compiler", "Software that translates source code into another executable form.", "Compilers can catch whole classes of errors before runtime."],
    ["Concurrency", "Managing multiple tasks whose execution overlaps.", "Concurrent work is not always parallel work."],
    ["Data structure", "A format for organizing data so operations are efficient.", "Choosing a data structure often matters more than micro-optimizing code."],
    ["Debugging", "The systematic process of locating and correcting defects.", "A reliable reproduction turns a mystery into a testable problem."],
    ["Dependency", "External code or a module another piece of software requires.", "Each dependency adds capability and supply-chain risk."],
    ["Encryption", "Transforming information so only authorized parties can read it.", "Encryption is strongest when key handling is strong too."],
    ["Function", "A reusable unit of behavior with defined inputs and outputs.", "Small functions are easier to test when each has one clear responsibility."],
    ["Git", "A distributed system for tracking changes to files over time.", "A focused commit is both a checkpoint and an explanation."],
    ["HTTP", "The request-response protocol used to exchange resources on the web.", "HTTP methods communicate intent as well as transport data."],
    ["Idempotency", "The property that repeating an operation has the same effect as doing it once.", "Idempotent endpoints make retries safer."],
    ["Immutability", "Treating a value as unchanged after it is created.", "Immutable data reduces hidden state changes and simplifies reasoning."],
    ["Index", "An auxiliary structure that speeds data lookup at a storage cost.", "Indexes improve reads but add work to writes."],
    ["Latency", "The delay between starting an operation and receiving its result.", "One avoided network round trip can beat many small code optimizations."],
    ["Loop", "A construct that repeats a block of work under defined conditions.", "Every loop needs a clear termination condition."],
    ["Middleware", "Code that runs between a request and its final handler.", "Middleware is useful for cross-cutting concerns such as headers and logging."],
    ["Normalization", "Organizing data to reduce duplication and inconsistent updates.", "Normalization improves integrity; selective denormalization can improve reads."],
    ["Recursion", "Solving a problem by reducing it to smaller instances of itself.", "Every recursive solution needs a base case."],
    ["Refactor", "Changing internal structure without changing observable behavior.", "Tests make refactoring safer by protecting behavior."],
    ["Repository", "A version-controlled home for code and its history.", "A useful repository includes the instructions needed to run it."],
    ["Runtime", "The environment in which a program executes.", "Code can compile correctly yet fail because runtime assumptions differ."],
    ["Schema", "A formal description of the shape and constraints of data.", "A schema turns vague expectations into enforceable boundaries."],
    ["Serialization", "Converting data into a format suitable for storage or transfer.", "Never deserialize untrusted input without validation."],
    ["Stack", "A last-in, first-out collection.", "Function call history is commonly represented as a call stack."],
    ["Test", "An executable claim about expected behavior.", "A strong test fails for the right reason before the fix is written."],
    ["Type", "A classification that defines allowed values and operations.", "Types document intent and can prevent invalid states."],
    ["Version control", "A system for recording, comparing, and coordinating changes.", "Short-lived branches and clear commits reduce integration friction."],
  ],
  finance: [
    ["Compound interest", "Growth earned on both the original amount and previously accumulated growth.", "Time can matter more than a slightly higher contribution rate."],
    ["Inflation", "A broad rise in prices that reduces purchasing power over time.", "Real return is approximately investment return minus inflation."],
    ["Diversification", "Spreading exposure so one outcome cannot dominate the whole portfolio.", "Diversification reduces concentration risk but cannot remove all risk."],
    ["Liquidity", "How quickly an asset can become cash without a large loss in value.", "Emergency money is usually kept in highly liquid assets."],
    ["Volatility", "The degree and speed of price movement over time.", "Volatility measures movement, not the certainty of permanent loss."],
    ["Asset", "A resource with current or potential economic value.", "Cash, bonds, shares, and property are common asset categories."],
    ["Liability", "A present financial obligation owed to another party.", "Net worth equals assets minus liabilities."],
    ["Equity", "Ownership value after liabilities are subtracted.", "A share of stock represents a fractional ownership claim."],
    ["Bond", "A debt instrument through which an issuer borrows from investors.", "Bond prices generally move opposite to market interest rates."],
    ["Index fund", "A fund designed to track a defined market index.", "Passive tracking often keeps turnover and fees comparatively low."],
    ["ETF", "A pooled investment fund whose shares trade on an exchange.", "An ETF’s market price can differ slightly from its underlying value."],
    ["Emergency fund", "Liquid savings reserved for unexpected essential expenses.", "Its purpose is resilience, not maximum investment return."],
    ["Budget", "A plan that assigns expected income to spending, saving, and goals.", "A useful budget reflects actual behavior and is reviewed regularly."],
    ["Cash flow", "Money entering and leaving over a period.", "Positive cash flow creates room for saving and flexibility."],
    ["Credit score", "A model-based estimate of how likely a borrower is to repay.", "Payment history and credit utilization often carry substantial weight."],
    ["Dividend", "A distribution a company makes to eligible shareholders.", "A dividend is part of total return, not free money."],
    ["Expense ratio", "Annual fund operating costs expressed as a percentage of assets.", "Small fee differences compound over long holding periods."],
    ["Market capitalization", "A company’s share price multiplied by shares outstanding.", "Market cap measures market value, not revenue or cash held."],
    ["Net worth", "The value of owned assets minus outstanding liabilities.", "Tracking direction over time is often more useful than comparing with others."],
    ["Opportunity cost", "The value of the best alternative forgone by a choice.", "Every use of money also gives up another possible use."],
    ["Principal", "The original amount invested or borrowed before interest.", "Payments on debt may be divided between principal and interest."],
    ["Return", "The gain or loss on an investment over a period.", "Total return includes both price change and income."],
    ["Risk tolerance", "The willingness and capacity to withstand uncertain outcomes.", "Capacity to take risk can differ from emotional willingness."],
    ["Savings rate", "The share of income set aside rather than spent.", "A sustainable savings rate is more useful than a short-lived extreme one."],
    ["Simple interest", "Interest calculated only on the original principal.", "Unlike compounding, prior interest does not itself earn interest."],
    ["Tax diversification", "Holding savings across accounts with different tax treatment.", "Different account types can provide flexibility when tax rules or income change."],
    ["Time value of money", "The principle that money available today can be worth more than the same amount later.", "Present value discounts a future sum by its required rate of return."],
    ["Yield", "Income from an asset expressed relative to its price or value.", "A higher yield can signal higher risk rather than a better bargain."],
    ["Rebalancing", "Restoring a portfolio to its intended allocation.", "Rebalancing systematically sells relative winners and adds to lagging allocations."],
    ["Dollar-cost averaging", "Investing a fixed amount at regular intervals.", "It reduces timing pressure but does not guarantee a profit."],
  ],
  stoicism: [
    ["Dichotomy of control", "Separate what depends on your choices from what does not.", "Effort belongs to you; outcomes also depend on the world."],
    ["Virtue", "Excellence of character expressed through wise action.", "Stoicism treats character, not comfort, as the central good."],
    ["Judgment", "The interpretation placed between an event and a response.", "Pausing to inspect a judgment creates room for a better action."],
    ["Amor fati", "A willingness to embrace reality and work with what occurs.", "Acceptance is not passivity; it is an accurate starting point."],
    ["Memento mori", "A reminder that life is finite.", "Remembering limits can clarify what deserves attention now."],
    ["Premeditatio malorum", "Calmly imagining setbacks so they can be met with preparation.", "The exercise aims at readiness, not worry."],
    ["View from above", "Mentally widening perspective beyond the immediate self.", "Distance can shrink an insult without dismissing a real problem."],
    ["Voluntary discomfort", "Choosing modest difficulty to train gratitude and adaptability.", "The practice should build capability, not become self-punishment."],
    ["Temperance", "Using restraint and proportion rather than excess.", "Moderation preserves freedom of choice."],
    ["Courage", "Acting rightly despite fear or difficulty.", "Courage is compatible with fear; it is not the absence of it."],
    ["Justice", "Treating others fairly and contributing to the common good.", "Stoic virtue is social, not merely private calm."],
    ["Wisdom", "Seeing circumstances clearly and choosing sound action.", "Wisdom includes knowing when more information is needed."],
    ["Assent", "The mind’s decision to accept an impression as true.", "An initial impression can be automatic; assent can be examined."],
    ["Impression", "The first appearance an event presents to the mind.", "Naming an impression as an impression weakens its claim to certainty."],
    ["Role ethics", "Meeting responsibilities arising from one’s relationships and commitments.", "A decision can be judged by the role and duty it serves."],
    ["Cosmopolitanism", "Seeing every person as part of one human community.", "The early Stoics described themselves as citizens of the world."],
    ["Equanimity", "Steady composure amid changing circumstances.", "Equanimity makes useful action easier; it does not erase emotion."],
    ["Discipline of desire", "Training wants toward what can be chosen well.", "Desiring guaranteed outcomes gives fortune control over peace."],
    ["Discipline of action", "Directing behavior toward justice and practical service.", "Intent becomes character through repeated action."],
    ["Discipline of assent", "Testing thoughts before treating them as facts.", "Ask what evidence an urgent story actually has."],
    ["Reserve clause", "Pursuing a goal while acknowledging conditions may prevent it.", "Add: I will do this, fate permitting."],
    ["Objective representation", "Describe an event without loaded conclusions.", "Replace ‘a disaster’ with the observable facts first."],
    ["Self-command", "The ability to guide action instead of being ruled by impulse.", "Self-command grows through small choices made consistently."],
    ["Gratitude", "Recognizing the value already present in ordinary life.", "Impermanence can make appreciation more vivid."],
    ["Adversity", "Difficulty used as material for practicing character.", "The obstacle can become a place to exercise patience or courage."],
    ["Indifference", "Something neither morally good nor bad in itself.", "Health and wealth may be preferred, yet character governs their use."],
    ["Present attention", "Returning effort to the action available now.", "Past and future matter, but action can only occur in the present."],
    ["Mutuality", "The idea that people are made to cooperate.", "A good life considers effects on the wider community."],
    ["Reflection", "Reviewing actions to learn without self-deception.", "A brief evening review can turn experience into guidance."],
    ["Prohairesis", "The faculty of deliberate choice and moral purpose.", "Epictetus located freedom in the quality of one’s choices."],
  ],
  science: [
    ["Atom", "The smallest unit of an element that retains its chemical identity.", "Most of an atom’s volume is the space around a tiny nucleus."],
    ["Cell", "The basic structural and functional unit of living organisms.", "Every known organism is made of one or more cells."],
    ["Gravity", "The attraction associated with mass and the curvature of spacetime.", "On Earth, gravity accelerates falling objects at roughly 9.8 metres per second squared."],
    ["Evolution", "Change in inherited traits of populations across generations.", "Natural selection is one mechanism of evolution, not its only source of change."],
    ["Photosynthesis", "The process by which organisms convert light energy into chemical energy.", "Plants release oxygen while using water and carbon dioxide to build sugars."],
    ["Plate tectonics", "The movement of rigid plates across Earth’s upper mantle.", "Plate boundaries concentrate many earthquakes and volcanoes."],
    ["DNA", "A molecule that stores hereditary instructions in living systems.", "Human DNA contains four principal nucleotide bases."],
    ["Ecosystem", "A community of organisms interacting with their physical environment.", "Energy flows through ecosystems while matter is repeatedly cycled."],
    ["Entropy", "A measure related to the number of microscopic arrangements of a system.", "In an isolated system, total entropy tends not to decrease."],
    ["Photon", "A quantum of electromagnetic radiation.", "Photon energy increases with frequency."],
    ["Black hole", "A region where gravity prevents even light from escaping beyond the event horizon.", "The event horizon is a boundary, not a solid surface."],
    ["Exoplanet", "A planet orbiting a star beyond the Solar System.", "Thousands of exoplanets have been confirmed using several detection methods."],
    ["Neutron star", "An extremely dense remnant left by some stellar explosions.", "A neutron star can pack more solar mass into a city-sized sphere."],
    ["Mitosis", "Cell division that produces two genetically similar daughter cells.", "Mitosis supports growth, maintenance, and repair."],
    ["Catalyst", "A substance that changes reaction rate without being consumed overall.", "Enzymes are biological catalysts."],
    ["Isotope", "Atoms of one element with different numbers of neutrons.", "Some isotopes are stable while others decay radioactively."],
    ["Magnetic field", "A field produced by moving charge and magnetic materials.", "Earth’s magnetic field helps deflect charged particles from the Sun."],
    ["Tectonic subduction", "The process in which one plate descends beneath another.", "Subduction recycles crustal material into Earth’s mantle."],
    ["Gene", "A DNA sequence that contributes to a functional product.", "Many traits are influenced by multiple genes and the environment."],
    ["Microbiome", "A community of microorganisms associated with an environment or host.", "The human gut microbiome varies with diet, age, and many other factors."],
    ["Supernova", "A powerful stellar explosion.", "Supernovae distribute newly formed elements into surrounding space."],
    ["Refraction", "The change in direction of a wave as its speed changes between media.", "A prism separates colours because wavelengths refract by different amounts."],
    ["pH", "A logarithmic measure related to hydrogen ion activity in a solution.", "A one-unit pH change represents a tenfold change on the scale."],
    ["Homeostasis", "The regulation of internal conditions within workable ranges.", "Sweating is one response that helps regulate body temperature."],
    ["Symbiosis", "A close biological interaction between different species.", "Symbiosis can benefit both organisms, one organism, or neither."],
    ["Half-life", "The time required for half of a radioactive sample to decay.", "Half-life is statistical and does not predict when one atom will decay."],
    ["Wave", "A disturbance that transfers energy through space or a medium.", "Waves can interfere constructively or destructively."],
    ["Climate", "Long-term patterns in weather conditions.", "Climate describes trends over decades; weather describes short-term conditions."],
    ["Scientific model", "A simplified representation used to explain and predict phenomena.", "A useful model is judged by evidence and the accuracy of its predictions."],
    ["Peer review", "Evaluation of scholarly work by other experts before publication.", "Peer review filters obvious weaknesses but does not make a result infallible."],
  ],
  history: [
    ["Agricultural Revolution", "The long transition from foraging to settled farming.", "Food surplus supported denser settlements and specialized work."],
    ["Writing", "Systems of visible marks used to record language and information.", "Early writing developed independently in more than one region."],
    ["Silk Roads", "Overlapping trade routes connecting communities across Eurasia.", "Goods travelled alongside religions, technologies, art, and disease."],
    ["Roman Republic", "The period when Rome was governed through elected offices and assemblies.", "Its institutions influenced later vocabulary about civic government."],
    ["Magna Carta", "A 1215 agreement that placed stated limits on royal power.", "Later generations gave the charter meanings beyond its immediate dispute."],
    ["Printing press", "Mechanized movable-type printing that accelerated text reproduction.", "Cheaper copies widened the circulation of religious, scientific, and political ideas."],
    ["Renaissance", "A period of artistic and intellectual change drawing on classical traditions.", "Renaissance developments varied greatly across European regions."],
    ["Reformation", "Religious movements that fractured western European Christianity.", "Print helped arguments circulate far beyond their place of origin."],
    ["Scientific Revolution", "Changes in methods and institutions for studying nature.", "Measurement, mathematical models, and repeatable observation gained authority."],
    ["Enlightenment", "Intellectual movements emphasizing reason, inquiry, and debate over authority.", "Enlightenment thinkers disagreed sharply on freedom, empire, and equality."],
    ["Industrial Revolution", "The shift toward mechanized production and fossil-fuel energy.", "It transformed work, cities, transport, consumption, and the environment."],
    ["Abolitionism", "Movements seeking to end slavery and the slave trade.", "Enslaved people’s resistance was central to the destruction of slavery."],
    ["Haitian Revolution", "The successful antislavery revolution that created independent Haiti.", "It was the only large-scale slave revolt to found a state."],
    ["Meiji Restoration", "The political transformation that accelerated Japan’s state-led modernization.", "Reform combined imported institutions with Japanese political priorities."],
    ["First World War", "A global conflict from 1914 to 1918 centred on rival alliances and empires.", "Its effects redrew borders and destabilized societies far beyond Europe."],
    ["Women’s suffrage", "Campaigns for women’s right to vote.", "Victory arrived at different times and often excluded women by race or class."],
    ["Decolonization", "The dissolution of colonial empires and creation of independent states.", "Independence movements used diplomacy, mass politics, culture, and armed struggle."],
    ["Cold War", "A global rivalry led by the United States and Soviet Union after 1945.", "Competition shaped conflicts, alliances, science, and daily life worldwide."],
    ["Green Revolution", "The spread of high-yield crops, irrigation, fertilizers, and agricultural research.", "It raised food output while creating new environmental and distribution challenges."],
    ["Non-Aligned Movement", "A coalition seeking autonomy from Cold War power blocs.", "Its members were diverse and did not remain neutral on every issue."],
    ["Indus Valley Civilization", "An urban Bronze Age civilization in South Asia.", "Its cities used standardized weights and sophisticated drainage."],
    ["Mali Empire", "A major West African empire enriched by trade and agriculture.", "Mansa Musa’s pilgrimage made Mali’s wealth famous across a wide region."],
    ["Song dynasty", "A Chinese dynasty noted for commercial, technological, and cultural development.", "Movable type, gunpowder use, and maritime trade expanded during the period."],
    ["Inca road system", "A vast Andean network linking the Inca state.", "Runners carried information along routes crossing extreme terrain."],
    ["Polynesian navigation", "Wayfinding across the Pacific using stars, waves, winds, and ecology.", "Navigators settled islands across immense ocean distances without modern instruments."],
    ["Black Death", "The devastating fourteenth-century plague pandemic.", "Population loss reshaped labour, belief, public health, and political relations."],
    ["Indian independence", "The long struggle that ended British colonial rule in 1947.", "Mass movements existed alongside constitutional work, labour action, and revolutionary politics."],
    ["Civil rights movement", "Organized struggle against racial segregation and disenfranchisement in the United States.", "Local organizing sustained national legal and political victories."],
    ["Moon landing", "Apollo 11’s 1969 crewed landing on the Moon.", "The mission depended on hundreds of thousands of people across many specialties."],
    ["World Wide Web", "A linked information system proposed by Tim Berners-Lee at CERN.", "The web uses the internet but is not the same thing as the internet."],
  ],
  psychology: [
    ["Working memory", "The limited system used to hold and manipulate information briefly.", "Chunking related items reduces the load placed on working memory."],
    ["Confirmation bias", "The tendency to favor information that supports an existing belief.", "Actively seeking disconfirming evidence improves important decisions."],
    ["Cognitive dissonance", "Discomfort caused by inconsistent beliefs, values, or actions.", "People may change a belief or justify a choice to reduce dissonance."],
    ["Classical conditioning", "Learning through association between stimuli.", "A previously neutral cue can begin to trigger a learned response."],
    ["Operant conditioning", "Learning shaped by consequences that follow behavior.", "Reinforcement increases behavior; punishment aims to reduce it."],
    ["Growth mindset", "The belief that abilities can develop through effective effort and learning.", "A growth mindset works best with strategy, feedback, and realistic practice."],
    ["Fundamental attribution error", "Overweighting personality and underweighting context when judging others.", "For our own actions, we more readily notice situational constraints."],
    ["Availability heuristic", "Judging likelihood by how easily examples come to mind.", "Vivid recent events can feel more common than statistics show."],
    ["Anchoring", "Relying too heavily on an initial number or piece of information.", "Even arbitrary anchors can influence later estimates."],
    ["Loss aversion", "The tendency for losses to feel more significant than equivalent gains.", "Framing the same choice as a loss or gain can change decisions."],
    ["Dunning–Kruger effect", "A pattern in which limited knowledge can hinder accurate self-assessment.", "Expertise can also make people underestimate what novices find difficult."],
    ["Spotlight effect", "Overestimating how much other people notice our appearance or mistakes.", "Most people are occupied with their own concerns."],
    ["Mere-exposure effect", "Developing greater preference for something after repeated exposure.", "Familiarity can influence liking even without deliberate evaluation."],
    ["Peak-end rule", "Remembering an experience largely by its most intense point and ending.", "A strong conclusion can reshape how an entire experience is recalled."],
    ["Zeigarnik effect", "Remembering interrupted or unfinished tasks more readily than completed ones.", "A written next step can reduce the mental pull of unfinished work."],
    ["Social proof", "Using other people’s behavior as evidence of what is appropriate.", "Social proof becomes stronger when the situation is uncertain."],
    ["Self-efficacy", "Belief in one’s ability to perform actions needed for a task.", "Small mastery experiences are a powerful source of self-efficacy."],
    ["Intrinsic motivation", "Doing an activity because it is inherently satisfying.", "Autonomy, competence, and connection can support intrinsic motivation."],
    ["Extrinsic motivation", "Doing an activity for an external reward or consequence.", "External rewards can help start behavior but may change its meaning."],
    ["Habit loop", "A recurring pattern of cue, behavior, and consequence.", "Changing the environment can be easier than relying on willpower at the cue."],
    ["Selective attention", "Focusing on some information while filtering competing input.", "Attention is limited, so noticing one thing can hide another."],
    ["Priming", "Exposure to one stimulus influencing a later response.", "Priming effects depend strongly on context and experimental design."],
    ["Placebo effect", "A real change associated with expectations and treatment context.", "Placebo responses do not mean symptoms were imaginary."],
    ["Emotional regulation", "Processes used to influence which emotions occur and how they are expressed.", "Reframing a situation is one regulation strategy."],
    ["Learned helplessness", "Reduced effort after repeated experiences of lacking control.", "Restoring small, genuine choices can help rebuild agency."],
    ["Recency effect", "Improved recall for items encountered near the end of a sequence.", "Spacing and retrieval practice reduce overreliance on recency."],
    ["Halo effect", "Allowing one positive impression to influence unrelated judgments.", "Separating evaluation criteria reduces halo-driven decisions."],
    ["Sunk-cost effect", "Continuing because of past investment rather than future value.", "Past costs cannot be recovered; compare only the options available now."],
    ["Empathy gap", "Underestimating how strongly a different emotional state affects decisions.", "Make important plans before hunger, anger, or fatigue peaks."],
    ["Metacognition", "Awareness and regulation of one’s own thinking and learning.", "Testing recall provides better feedback than rereading alone."],
  ],
  productivity: [
    ["Time blocking", "Assigning a defined period to one category of work.", "A block should include a clear outcome, not just a project name."],
    ["Single-tasking", "Giving one meaningful task undivided attention.", "Task switching leaves attention residue that slows the next task."],
    ["Two-minute start", "Reducing a task to an action small enough to begin immediately.", "Starting lowers emotional friction even when the full task takes longer."],
    ["Weekly review", "A regular check of commitments, progress, and next actions.", "Reviewing prevents plans from becoming stale lists."],
    ["Capture system", "One trusted place for collecting tasks and ideas.", "A capture tool only works when it is emptied and clarified regularly."],
    ["Next action", "The smallest visible step that moves an outcome forward.", "Specific verbs make next actions easier to start."],
    ["Deep work", "Focused effort on cognitively demanding work without distraction.", "Protecting fewer high-quality hours can outperform a full day of interruption."],
    ["Shutdown ritual", "A brief routine for closing open loops at the end of work.", "Writing tomorrow’s first task helps the mind disengage."],
    ["Energy management", "Matching work demands to predictable changes in alertness.", "Schedule hard thinking when your energy is usually strongest."],
    ["Batching", "Grouping similar small tasks into one session.", "Batching reduces repeated setup and context switching."],
    ["Default calendar", "A reusable weekly template for recurring priorities.", "The template is a guide that can adapt, not a rigid scorecard."],
    ["Implementation intention", "A plan stated as: when this cue occurs, I will take this action.", "Linking behavior to a cue makes follow-through more automatic."],
    ["Environment design", "Changing surroundings so useful actions are easier and distractions harder.", "Moving a phone out of reach removes repeated decisions."],
    ["Definition of done", "A concrete condition that marks a task complete.", "Clear finish lines prevent endless polishing."],
    ["Priority limit", "Restricting the number of active priorities.", "If everything is urgent, trade-offs remain hidden."],
    ["Buffer time", "Unscheduled space reserved for delays and recovery.", "A calendar filled to 100 percent is already overcommitted."],
    ["Decision rule", "A pre-made rule for a recurring choice.", "Rules reduce decision fatigue when values are already clear."],
    ["Meeting agenda", "A short statement of purpose, topics, and desired decisions.", "A meeting without a decision or shared work may be a message instead."],
    ["Focus cue", "A repeated signal that marks the start of concentrated work.", "Using the same place or sound can make entry into focus easier."],
    ["Progress log", "A brief record of completed work and lessons.", "Visible progress improves planning and motivation."],
    ["Constraint", "A deliberate limit that narrows options and encourages completion.", "A time limit can prevent low-value perfectionism."],
    ["Recovery", "Rest that restores the capacity for useful effort.", "Sleep and breaks are inputs to performance, not rewards after it."],
    ["Friction audit", "Looking for small obstacles that repeatedly block a behavior.", "Remove one click, search, or setup step from a frequent task."],
    ["Inbox zero-ish", "Keeping communication processed enough that important items are trusted.", "The goal is clarity, not maintaining an empty counter."],
    ["Project milestone", "A meaningful checkpoint showing a project has changed state.", "Milestones make long work observable and easier to coordinate."],
    ["Work in progress limit", "A cap on how many tasks may be active at once.", "Finishing frees capacity faster than starting more."],
    ["Precommitment", "Making a future choice harder to abandon.", "Public deadlines and prepared environments can support precommitment."],
    ["Template", "A reusable starting structure for recurring work.", "Templates preserve decisions while leaving room for judgment."],
    ["After-action review", "A short reflection on what happened, why, and what changes next.", "Review the process while evidence is still fresh."],
    ["Minimum viable day", "A small baseline that keeps essential routines alive during disruption.", "A humane baseline prevents one difficult day from becoming abandonment."],
  ],
};

for (const category of Object.keys(fallbackSeeds) as LearningCategory[]) {
  if (fallbackSeeds[category].length !== 30) {
    throw new Error(`${category} must contain exactly 30 fallback lessons`);
  }
}
